# Generated by Django 3.0.6 on 2020-06-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
