# Generated by Django 3.0.6 on 2020-11-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='company',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='registration_date',
        ),
    ]
