# Generated by Django 3.0.6 on 2020-10-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20201016_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='listing_slug',
        ),
        migrations.AddField(
            model_name='contact',
            name='listing_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
