# Generated by Django 3.0.6 on 2020-09-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('UA', 'Ukrainian'), ('RU', 'Russian'), ('EN', 'English')], max_length=20),
        ),
    ]
