# Generated by Django 3.0.6 on 2020-07-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200701_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.CharField(choices=[('Softcover', "М'ягка"), ('Hardcover', 'Тверда')], max_length=9),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('UA', 'Українська'), ('RU', 'Російська'), ('EN', 'Англійська')], max_length=9),
        ),
    ]
