# Generated by Django 3.0.6 on 2020-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200920_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
