# Generated by Django 3.0.6 on 2020-06-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200602_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='new',
            new_name='is_new',
        ),
    ]
