# Generated by Django 3.0.6 on 2020-06-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200602_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.CharField(choices=[('Softcover', 'Softcover'), ('Hardcover', 'Hardcover')], max_length=9),
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
