# Generated by Django 3.0.6 on 2020-07-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200701_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.CharField(choices=[("М'ягка", 'Softcover'), ('Тверда', 'Hardcover')], max_length=9),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Українська', 'UA'), ('Російська', 'RU'), ('Англійська', 'EN')], max_length=20),
        ),
    ]
