# Generated by Django 3.0.6 on 2020-07-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200701_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
