# Generated by Django 3.0.6 on 2020-07-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200701_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_4',
        ),
    ]
