# Generated by Django 3.0.6 on 2020-11-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('listings', '0010_auto_20201103_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='owner_books', to='owners.Owner'),
            preserve_default=False,
        ),
    ]
